parameters:
  environment: 'NOT_DEFINE'
  buildConfiguration: 'NOT_DEFINE'
  outputDirectory: 'NOT_DEFINE'
  keystoreFile: 'NOT_DEFINE'
  keystorePassword: 'NOT_DEFINE'
  keystoreAlias: 'NOT_DEFINE'
  keyPassword: 'NOT_DEFINE'
  projectPath: 'NOT_DEFINE'
  netCoreVersion: '3.0.x'
  nugetVersion: '5.3.1'

jobs:
  - job: 
    displayName: 'Building ${{ parameters.environment }}'
    steps:
      # Installing .NET Core 3.0.x
      # Latest reference assemblies and build system requires .NET Core.
      - task: UseDotNet@2
        displayName: Use .Net Core sdk ${{ parameters.netCoreVersion }}
        inputs:
          packageType: 'sdk'
          version: '${{ parameters.netCoreVersion }}'
          
      # Use Bash to tell what version Xamarin and Mono to use when compiling app.
      - task: Bash@3
        displayName: Bash script copy Xamarin Android mono
        inputs:
          targetType: 'inline'
          script: |
            sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 6_4_0
      
      # Use Nuget 5.3.1
      - task: NuGetToolInstaller@1
        displayName: 'Use Nuget ${{ parameters.nugetVersion }}'
        inputs:
          versionSpec: '${{ parameters.nugetVersion }}'
      
      # Download Mono 6.4.0 to build app with C# 8, iOS 13 and Android 10.
      - task: Boots@1
        displayName: Install Xamarin.Android Mono 6.4
        inputs:
          uri: 'https://download.mono-project.com/archive/6.4.0/macos-10-universal/MonoFramework-MDK-6.4.0.187.macos10.xamarin.universal.pkg'
      
      # Restore Nugets.
      - task: MSBuild@1
        displayName: 'Restore Nuget'
        inputs:
          solution: '${{ parameters.projectPath }}'
          configuration: '$(buildConfiguration)'
          msbuildArguments: '/t:Restore'
          
      # Build Xamarin Android project.
      - task: XamarinAndroid@1
        displayName: 'Build PlanningPoker Android'
        inputs:
          projectFile: '${{ parameters.projectPath }}'
          outputDirectory: ${{ parameters.outputDirectory }}
          configuration: ${{ parameters.buildConfiguration }}
          
      # Singing and aligning APK files.
      - task: AndroidSigning@3
        displayName: 'Singing and Aligning APK files(s)'
        inputs:
          apkFiles: '${{ parameters.outputDirectory }}/*.apk'
          apksign: true
          apksignerKeystoreFile: ${{ parameters.keystoreFile }}
          apksignerKeystorePassword: ${{ parameters.keystorePassword }}
          apksignerKeystoreAlias: ${{ parameters.keystoreAlias }}
          apksignerKeyPassword: ${{ parameters.keyPassword }}
          #apksignerArguments: --out ${{ parameters.outputDirectory }}/app.${{ parameters.environment }}.release.apk
          zipalign: true
      
      # Publishing artifact from this stage.
      - task: PublishBuildArtifacts@1
        displayName: 'Publishing artifact to: ${{ parameters.outputDirectory }}'
        inputs:
          #TargetPath: '${{ parameters.outputDirectory}}/app.${{ parameters.environment }}.release.apk'
          #ArtifactName: build_${{ parameters.environment }}
          pathToPublish: ${{ parameters.outputDirectory }}

      - task: AppCenterDistribute@3
        inputs:
          serverEndpoint: 'AppCenter'
          appSlug: 'flow/Planning-Poker'
          appFile: '${{ parameters.outputDirectory }}/*.apk'
          symbolOption: 'Android'
          releaseNotesOption: 'input'
          releaseNotesInput: 'New version'
          destinationType: 'groups'
